// Local-only preview. Read-only proxy to the user's public Komari API; no credentials or admin routes.
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const upstream='https://shell.status.moe';
const allowed=new Set(['/api/public','/api/nodes','/api/version','/api/records/load','/api/records/ping','/api/task/ping']);
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname==='/favicon.ico'&&req.method==='GET'){const image=await fetch(upstream+'/favicon.ico',{signal:AbortSignal.timeout(10000)});res.writeHead(image.status,{'Content-Type':image.headers.get('content-type')||'image/x-icon'});res.end(Buffer.from(await image.arrayBuffer()));return;}if(url.pathname.startsWith('/api/')){let options={signal:AbortSignal.timeout(15000)};if(url.pathname==='/api/rpc2'&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>4096){res.writeHead(413);res.end();return;}}const j=JSON.parse(body);if(j.method!=='common:getNodesLatestStatus')throw new Error('Only public status queries allowed');options={...options,method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:j.method,id:1})};}else if((!allowed.has(url.pathname)&&!/^\/api\/recent\/[a-f0-9-]{36}$/.test(url.pathname))||req.method!=='GET'){res.writeHead(403);res.end();return;}const response=await fetch(upstream+url.pathname+url.search,options);res.writeHead(response.status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(await response.text());return;}
const relative=(url.pathname==='/'||/^\/instance\/[^/]+$/.test(url.pathname))?'dist/index.html':url.pathname.startsWith('/themes/aero/')?url.pathname.slice('/themes/aero/'.length):null;if(!relative){res.writeHead(404);res.end();return;}const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep))throw new Error('Invalid path');const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.json':'application/json'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(await readFile(file));}catch{res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({status:'error',message:'预览服务无法连接数据源，请稍后重试。'}));}}).listen(4173,'127.0.0.1',()=>console.log('Aero preview: http://127.0.0.1:4173 (live public data)'));
